import { Item } from './types';

export const fakeListings: Item[] = [{
    id: 123,
    name: 'Noodles',
    description: 'Spicy and cheesy noodles',
    price: 700,
    quantity: '2',
    weight:'20',
    nutrition:'50',
    veg: "Veg",
    spl: "Not Special",
}, {
    id: 345,
    name: 'Bun',
    description: 'From the 1990s, a classic!',
    price: 50,
    quantity: '3',
    weight:'20',
    nutrition:'50',
    veg: "Non-Veg",
    spl: "Not Special",
}, {
    id: 456,
    name: 'Bread',
    description: 'Soft and sweet',
    price: 100,
    quantity: '4',
    weight:'20',
    nutrition:'50',
    veg: "Veg",
    spl: "Not Special",
}];

export const fakeMyListings: Item[] = [{
    id: 789,
    name: 'Cake',
    description: 'Rich with cream',
    price: 75,
    quantity: '2',
    weight:'20',
    nutrition:'50',
    veg: "Non-Veg",
    spl: "Not Special",
}, {
    id: 234,
    name: 'Roll',
    description: 'All types of rolls are available',
    price: 80,
    quantity: '2',
    weight:'20',
    nutrition:'60',
    veg: "Veg",
    spl: "Not Special",
}, {
    id: 987,
    name: 'Momos',
    description: 'Tasty momos with sauce',
    price: 75,
    quantity: '2',
    weight:'20',
    nutrition:'100',
    veg: "Non:Veg",
    spl: "Not Special",
}];